### ISSUE TITLE
facade strategy work

### ISSUE THREAD

**Issue by sgoggins** [brianwarner/facade#21]
We are looking at incorporating the significant features of facade into the ghdata project http://github.com/OSSHealth/ghdata ... (to be renamed soon)

What are your thoughts on gathering repository information using https://github.com/nodegit/nodegit

Instead of the strategy facade employs? 

Asking for a friend.

**Comment by brianwarner** [comment]
There are a few really core activities (marked [*]) that happen in the Facade workflow:
1) Feed the database with project name and repo URL
2) Some stuff happens to clone or pull repos and attempt error handling [*]
3) Facade walks the git log and feeds the analysis_data table [*]
4) Facade figures out how author/committer emails align to known aliases and affiliations [*]
5) Analysis data is cached [*]
6) Display the data and export spreadsheets

For background, for simple stuff (like cloning and pulling git repos or traversing the git log) I have preferred not to use external libraries because it's really basic stuff and I want to know how it works when something fails.  In some cases you hit corner cases (like a git rebase or where a branch gets deleted) where the pull fails, and I've added some error handling that tries to fix things without requiring user intervention.  While it involves more lines of code, doing things directly in Python and calling git's porcelain commands reduces the overall complexity.  For a one-maintainer-show, this has been the most efficient way to do things... but of course I'm open to conversation on it.

At first read, it looks like nodegit could directly replace 2 and 3, so long as it can collect the same per-file info within each patch.  Do you know if there's new or better functionality it provides beyond what's already built into Facade that would justify the time and effort of integration?
